### ISSUE TITLE
Update link to new VILLASweb documentation

### ISSUE THREAD

**Issue by stv0g** [VILLASframework/web#311]
In GitLab by @stv0g on Apr 27, 2022, 15:30

**Comment by iripiri** [comment]
Hi @stv0g,
which link should replace the old link?

**Comment by stv0g** [comment]
Hi @iripiri,

the new URL for the VILLASweb documentation is here: https://villas.fein-aachen.org/docs/web/

Cheers,
Steffen

**Comment by iripiri** [comment]
Thanks!
